# =====================================================================
# 🛡️ VESSEL / NOVA CYBER-VAULT RUNTIME SDK 🛡️
# Official Python Client Library
# Lead Systems Architect: juniorsir
# =====================================================================

import os
import time
import random
import subprocess
from typing import List, Dict, Optional

class Vessel:
    """
    Sanskrit-Architected Linux Anonymity & Hardened Sandbox SDK
    """
    def __init__(
        self,
        mool: str = "/",
        karya: str = "/bin/bash",
        sangjna: str = "vault-node",
        smriti: str = "512MB",
        shakti: float = 1.0,
        kendra: Optional[str] = None,
        tejas: Optional[str] = None,
        vayu: Optional[List[str]] = None,
        gati: Optional[str] = None,
        bhaar: Optional[str] = None,
        sthapana: Optional[str] = None,
        paryavaran: Optional[Dict[str, str]] = None,
        # 🛡️ Elite Cybersecurity & Privacy Suite
        chhadm: Optional[str] = None,     # 🎭 MAC Spoofing ('random')
        gupt: Optional[str] = None,       # 🧅 Tor Transparent Tunnel ('tor')
        ekant: bool = False,              # 🏝️ Air-Gapped Solitude Mode
        bhasma: bool = False,             # 🔥 Anti-forensic RAM shredding
        maya: Optional[str] = None,       # 🔮 Syscall Honeypot ('trap')
        # Hardening & Isolation
        sadasya: str = "root",
        kavach: str = "strict",
        adhikar: Optional[str] = "-SYS_BOOT -SYS_TIME",
        kala: str = "virtual",
        suraksha: Optional[str] = None,
    ):
        self.mool = mool
        self.karya = karya
        self.sangjna = sangjna
        self.smriti = smriti
        self.shakti = shakti
        self.kendra = kendra
        self.tejas = tejas
        self.vayu = vayu or []
        self.gati = gati
        self.bhaar = bhaar
        self.sthapana = sthapana
        self.paryavaran = paryavaran or {}
        self.chhadm = chhadm
        self.gupt = gupt
        self.ekant = ekant
        self.bhasma = bhasma
        self.maya = maya
        self.sadasya = sadasya
        self.kavach = kavach
        self.adhikar = adhikar
        self.kala = kala
        self.suraksha = suraksha
        
        self.card_path = f"/tmp/Patra.{int(time.time())}.{random.randint(100, 999)}"

    def generate_card(self) -> str:
        """Generates the declarative YAML Patra manifest card on disk."""
        lines = [
            "# Generated by vessel-sdk (Python)",
            f'Mool: "{self.mool}"',
            f'Karya: "{self.karya}"',
            f'Sangjna: "{self.sangjna}"',
            f'Smriti: "{self.smriti}"',
            f'Shakti: {self.shakti}',
            f'Sadasya: "{self.sadasya}"',
            f'Kavach: "{self.kavach}"',
            f'Kala: "{self.kala}"',
        ]
        
        if self.sthapana: lines.append(f'Sthapana: "{self.sthapana}"')
        if self.kendra: lines.append(f'Kendra: "{self.kendra}"')
        if self.tejas: lines.append(f'Tejas: "{self.tejas}"')
        if self.gati: lines.append(f'Gati: "{self.gati}"')
        if self.bhaar: lines.append(f'Bhaar: "{self.bhaar}"')
        if self.adhikar: lines.append(f'Adhikar: "{self.adhikar}"')
        if self.suraksha: lines.append(f'Suraksha: "{self.suraksha}"')
        
        # Privacy Suite
        if self.chhadm: lines.append(f'Chhadm: "{self.chhadm}"')
        if self.gupt: lines.append(f'Gupt: "{self.gupt}"')
        if self.ekant: lines.append('Ekant: "true"')
        if self.bhasma: lines.append('Bhasma: "true"')
        if self.maya: lines.append(f'Maya: "{self.maya}"')

        if self.vayu:
            lines.append("Vayu:")
            for v in self.vayu:
                lines.append(f'  - "{v}"')

        if self.paryavaran:
            lines.append("Paryavaran:")
            for k, v in self.paryavaran.items():
                lines.append(f'  {k}: "{v}"')

        yaml_content = "\n".join(lines) + "\n"
        with open(self.card_path, "w") as f:
            f.write(yaml_content)
        return yaml_content

    def run(self, quiet: bool = False) -> subprocess.CompletedProcess:
        """Boots the sandbox synchronously and returns the completed process."""
        self.generate_card()
        cmd = ["sudo", "vessel", "-q", self.card_path] if quiet else ["sudo", "vessel", self.card_path]
        try:
            result = subprocess.run(cmd, text=True, capture_output=True)
            return result
        finally:
            self.clean()

    def clean(self):
        """Deletes the ephemeral manifest card."""
        if os.path.exists(self.card_path):
            os.remove(self.card_path)

    @staticmethod
    def clean_all():
        subprocess.run(["sudo", "vessel", "clean"])

    @staticmethod
    def launch_tor():
        subprocess.run(["sudo", "vessel", "tor"])

    @staticmethod
    def run_diagnostic_test():
        subprocess.run(["sudo", "vessel", "test"])
