use std::collections::HashMap;
use std::fs;
use std::path::PathBuf;
use std::process::Command;
use std::time::{SystemTime, UNIX_EPOCH};

#[derive(Debug, Clone)]
pub struct VesselOptions {
    pub mool: String,
    pub karya: String,
    pub sangjna: String,
    pub smriti: String,
    pub shakti: f32,
    pub kendra: Option<String>,
    pub tejas: Option<String>,
    pub vayu: Vec<String>,
    pub gati: Option<String>,
    pub bhaar: Option<String>,
    pub sthapana: Option<String>,
    pub paryavaran: HashMap<String, String>,
    pub chhadm: Option<String>,
    pub gupt: Option<String>,
    pub ekant: bool,
    pub bhasma: bool,
    pub maya: Option<String>,
    pub sadasya: String,
    pub kavach: String,
    pub adhikar: Option<String>,
    pub kala: String,
    pub suraksha: Option<String>,
}

impl Default for VesselOptions {
    fn default() -> Self {
        Self {
            mool: "/".to_string(),
            karya: "/bin/bash".to_string(),
            sangjna: "vault-node".to_string(),
            smriti: "512MB".to_string(),
            shakti: 1.0,
            kendra: None, tejas: None, vayu: Vec::new(), gati: None, bhaar: None, sthapana: None,
            paryavaran: HashMap::new(), chhadm: None, gupt: None, ekant: false, bhasma: false, maya: None,
            sadasya: "root".to_string(), kavach: "strict".to_string(),
            adhikar: Some("-SYS_BOOT -SYS_TIME".to_string()), kala: "virtual".to_string(), suraksha: None,
        }
    }
}

pub struct VesselClient {
    pub opts: VesselOptions,
    pub card_path: PathBuf,
}

impl VesselClient {
    pub fn new(opts: VesselOptions) -> Self {
        let ts = SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_secs();
        let card_path = PathBuf::from(format!("/tmp/Patra.{}.{}", ts, rand::random::<u16>()));
        Self { opts, card_path }
    }

    pub fn generate_card(&self) -> String {
        let mut lines = vec![
            "# Generated by vessel-sdk (Rust)".to_string(),
            format!("Mool: \"{}\"", self.opts.mool),
            format!("Karya: \"{}\"", self.opts.karya),
            format!("Sangjna: \"{}\"", self.opts.sangjna),
            format!("Smriti: \"{}\"", self.opts.smriti),
            format!("Shakti: {:.1}", self.opts.shakti),
            format!("Sadasya: \"{}\"", self.opts.sadasya),
        ];

        if let Some(ref val) = self.opts.sthapana { lines.push(format!("Sthapana: \"{}\"", val)); }
        if let Some(ref val) = self.opts.kendra { lines.push(format!("Kendra: \"{}\"", val)); }
        if let Some(ref val) = self.opts.tejas { lines.push(format!("Tejas: \"{}\"", val)); }
        if let Some(ref val) = self.opts.gati { lines.push(format!("Gati: \"{}\"", val)); }
        if let Some(ref val) = self.opts.bhaar { lines.push(format!("Bhaar: \"{}\"", val)); }
        if let Some(ref val) = self.opts.adhikar { lines.push(format!("Adhikar: \"{}\"", val)); }
        if let Some(ref val) = self.opts.suraksha { lines.push(format!("Suraksha: \"{}\"", val)); }
        if let Some(ref val) = self.opts.chhadm { lines.push(format!("Chhadm: \"{}\"", val)); }
        if let Some(ref val) = self.opts.gupt { lines.push(format!("Gupt: \"{}\"", val)); }
        if self.opts.ekant { lines.push("Ekant: \"true\"".to_string()); }
        if self.opts.bhasma { lines.push("Bhasma: \"true\"".to_string()); }
        if let Some(ref val) = self.opts.maya { lines.push(format!("Maya: \"{}\"", val)); }

        if !self.opts.vayu.is_empty() {
            lines.push("Vayu:".to_string());
            for v in &self.opts.vayu { lines.push(format!("  - \"{}\"", v)); }
        }
        if !self.opts.paryavaran.is_empty() {
            lines.push("Paryavaran:".to_string());
            for (k, v) in &self.opts.paryavaran { lines.push(format!("  {}: \"{}\"", k, v)); }
        }

        let content = lines.join("\n") + "\n";
        let _ = fs::write(&self.card_path, &content);
        content
    }

    pub fn run(&self, quiet: bool) -> std::io::Result<std::process::Output> {
        self.generate_card();
        let mut args = vec!["vessel"];
        if quiet { args.push("-q"); }
        args.push(self.card_path.to_str().unwrap());
        let res = Command::new("sudo").args(&args).output();
        self.clean();
        res
    }

    pub fn clean(&self) { let _ = fs::remove_file(&self.card_path); }
}
