package nova

import (
	"fmt"
	"math/rand"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"
)

type Options struct {
	Mool       string
	Karya      string
	Sangjna    string
	Smriti     string
	Shakti     float64
	Kendra     string
	Tejas      string
	Vayu       []string
	Gati       string
	Bhaar      string
	Sthapana   string
	Paryavaran map[string]string

	// 🛡️ Elite Cybersecurity & Privacy Suite
	Chhadm string // 🎭 MAC Spoofing ('random')
	Gupt   string // 🧅 Tor Transparent Tunnel ('tor')
	Ekant  bool   // 🏝️ Air-Gapped Solitude Mode
	Bhasma bool   // 🔥 Anti-forensic RAM shredding
	Maya   string // 🔮 Syscall Honeypot ('trap')

	// Hardening & Isolation
	Sadasya  string
	Kavach   string
	Adhikar  string
	Kala     string
	Suraksha string
}

type Client struct {
	opts     Options
	cardPath string
}

func NewClient(opts Options) *Client {
	if opts.Mool == "" { opts.Mool = "/" }
	if opts.Karya == "" { opts.Karya = "/bin/bash" }
	if opts.Sangjna == "" { opts.Sangjna = "vault-node" }
	if opts.Smriti == "" { opts.Smriti = "512MB" }
	if opts.Shakti == 0 { opts.Shakti = 1.0 }
	if opts.Sadasya == "" { opts.Sadasya = "root" }
	if opts.Kavach == "" { opts.Kavach = "strict" }

	rand.Seed(time.Now().UnixNano())
	cardPath := filepath.Join("/tmp", fmt.Sprintf("Patra.%d.%d", time.Now().Unix(), rand.Intn(900)+100))
	return &Client{opts: opts, cardPath: cardPath}
}

func (c *Client) GenerateCard() string {
	var lines []string
	lines = append(lines, "# Generated by vessel-sdk (Go)")
	lines = append(lines, fmt.Sprintf("Mool: \"%s\"", c.opts.Mool))
	lines = append(lines, fmt.Sprintf("Karya: \"%s\"", c.opts.Karya))
	lines = append(lines, fmt.Sprintf("Sangjna: \"%s\"", c.opts.Sangjna))
	lines = append(lines, fmt.Sprintf("Smriti: \"%s\"", c.opts.Smriti))
	lines = append(lines, fmt.Sprintf("Shakti: %.1f", c.opts.Shakti))
	lines = append(lines, fmt.Sprintf("Sadasya: \"%s\"", c.opts.Sadasya))

	if c.opts.Sthapana != "" { lines = append(lines, fmt.Sprintf("Sthapana: \"%s\"", c.opts.Sthapana)) }
	if c.opts.Kendra != "" { lines = append(lines, fmt.Sprintf("Kendra: \"%s\"", c.opts.Kendra)) }
	if c.opts.Tejas != "" { lines = append(lines, fmt.Sprintf("Tejas: \"%s\"", c.opts.Tejas)) }
	if c.opts.Gati != "" { lines = append(lines, fmt.Sprintf("Gati: \"%s\"", c.opts.Gati)) }
	if c.opts.Bhaar != "" { lines = append(lines, fmt.Sprintf("Bhaar: \"%s\"", c.opts.Bhaar)) }
	if c.opts.Kavach != "" { lines = append(lines, fmt.Sprintf("Kavach: \"%s\"", c.opts.Kavach)) }
	if c.opts.Adhikar != "" { lines = append(lines, fmt.Sprintf("Adhikar: \"%s\"", c.opts.Adhikar)) }
	if c.opts.Kala != "" { lines = append(lines, fmt.Sprintf("Kala: \"%s\"", c.opts.Kala)) }
	if c.opts.Suraksha != "" { lines = append(lines, fmt.Sprintf("Suraksha: \"%s\"", c.opts.Suraksha)) }

	if c.opts.Chhadm != "" { lines = append(lines, fmt.Sprintf("Chhadm: \"%s\"", c.opts.Chhadm)) }
	if c.opts.Gupt != "" { lines = append(lines, fmt.Sprintf("Gupt: \"%s\"", c.opts.Gupt)) }
	if c.opts.Ekant { lines = append(lines, "Ekant: \"true\"") }
	if c.opts.Bhasma { lines = append(lines, "Bhasma: \"true\"") }
	if c.opts.Maya != "" { lines = append(lines, fmt.Sprintf("Maya: \"%s\"", c.opts.Maya)) }

	if len(c.opts.Vayu) > 0 {
		lines = append(lines, "Vayu:")
		for _, v := range c.opts.Vayu { lines = append(lines, fmt.Sprintf("  - \"%s\"", v)) }
	}
	if len(c.opts.Paryavaran) > 0 {
		lines = append(lines, "Paryavaran:")
		for k, v := range c.opts.Paryavaran { lines = append(lines, fmt.Sprintf("  %s: \"%s\"", k, v)) }
	}

	content := strings.Join(lines, "\n") + "\n"
	_ = os.WriteFile(c.cardPath, []byte(content), 0644)
	return content
}

func (c *Client) Run(quiet bool) ([]byte, error) {
	c.GenerateCard()
	defer c.Clean()
	args := []string{"vessel"}
	if quiet { args = append(args, "-q") }
	args = append(args, c.cardPath)
	return exec.Command("sudo", args...).CombinedOutput()
}

func (c *Client) Clean() { _ = os.Remove(c.cardPath) }
