using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Text;

namespace NovaSdk
{
    public class VesselOptions
    {
        public string Mool { get; set; } = "/";
        public string Karya { get; set; } = "/bin/bash";
        public string Sangjna { get; set; } = "vault-node";
        public string Smriti { get; set; } = "512MB";
        public double Shakti { get; set; } = 1.0;
        public string? Kendra { get; set; }
        public string? Tejas { get; set; }
        public List<string> Vayu { get; set; } = new();
        public string? Gati { get; set; }
        public string? Bhaar { get; set; }
        public string? Sthapana { get; set; }
        public Dictionary<string, string> Paryavaran { get; set; } = new();
        public string? Chhadm { get; set; }
        public string? Gupt { get; set; }
        public bool Ekant { get; set; } = false;
        public bool Bhasma { get; set; } = false;
        public string? Maya { get; set; }
        public string Sadasya { get; set; } = "root";
        public string Kavach { get; set; } = "strict";
        public string? Adhikar { get; set; } = "-SYS_BOOT -SYS_TIME";
        public string Kala { get; set; } = "virtual";
        public string? Suraksha { get; set; }
    }

    public class NovaClient
    {
        private readonly VesselOptions _opts;
        private readonly string _cardPath;

        public NovaClient(VesselOptions? opts = null)
        {
            _opts = opts ?? new VesselOptions();
            _cardPath = $"/tmp/Patra.{DateTimeOffset.UtcNow.ToUnixTimeSeconds()}.{new Random().Next(100, 999)}";
        }

        public string GenerateCard()
        {
            var sb = new StringBuilder();
            sb.AppendLine("# Generated by vessel-sdk (C#)");
            sb.AppendLine($"Mool: \"{_opts.Mool}\"");
            sb.AppendLine($"Karya: \"{_opts.Karya}\"");
            sb.AppendLine($"Sangjna: \"{_opts.Sangjna}\"");
            sb.AppendLine($"Smriti: \"{_opts.Smriti}\"");
            sb.AppendLine($"Shakti: {_opts.Shakti:F1}");
            sb.AppendLine($"Sadasya: \"{_opts.Sadasya}\"");

            if (_opts.Sthapana != null) sb.AppendLine($"Sthapana: \"{_opts.Sthapana}\"");
            if (_opts.Kendra != null) sb.AppendLine($"Kendra: \"{_opts.Kendra}\"");
            if (_opts.Tejas != null) sb.AppendLine($"Tejas: \"{_opts.Tejas}\"");
            if (_opts.Gati != null) sb.AppendLine($"Gati: \"{_opts.Gati}\"");
            if (_opts.Bhaar != null) sb.AppendLine($"Bhaar: \"{_opts.Bhaar}\"");
            if (_opts.Adhikar != null) sb.AppendLine($"Adhikar: \"{_opts.Adhikar}\"");
            if (_opts.Suraksha != null) sb.AppendLine($"Suraksha: \"{_opts.Suraksha}\"");
            if (_opts.Chhadm != null) sb.AppendLine($"Chhadm: \"{_opts.Chhadm}\"");
            if (_opts.Gupt != null) sb.AppendLine($"Gupt: \"{_opts.Gupt}\"");
            if (_opts.Ekant) sb.AppendLine("Ekant: \"true\"");
            if (_opts.Bhasma) sb.AppendLine("Bhasma: \"true\"");
            if (_opts.Maya != null) sb.AppendLine($"Maya: \"{_opts.Maya}\"");

            if (_opts.Vayu.Count > 0)
            {
                sb.AppendLine("Vayu:");
                foreach (var v in _opts.Vayu) sb.AppendLine($"  - \"{v}\"");
            }
            if (_opts.Paryavaran.Count > 0)
            {
                sb.AppendLine("Paryavaran:");
                foreach (var kv in _opts.Paryavaran) sb.AppendLine($"  {kv.Key}: \"{kv.Value}\"");
            }

            var content = sb.ToString();
            File.WriteAllText(_cardPath, content);
            return content;
        }

        public string Run(bool quiet = false)
        {
            GenerateCard();
            try
            {
                var args = quiet ? $"-q {_cardPath}" : _cardPath;
                var psi = new ProcessStartInfo
                {
                    FileName = "sudo",
                    Arguments = $"vessel {args}",
                    RedirectStandardOutput = true,
                    RedirectStandardError = true,
                    UseShellExecute = false
                };
                using var proc = Process.Start(psi);
                proc?.WaitForExit();
                return proc?.StandardOutput.ReadToEnd() ?? "";
            }
            finally { Clean(); }
        }

        public void Clean() { if (File.Exists(_cardPath)) File.Delete(_cardPath); }
    }
}
