/**
 * 🛡️ VESSEL / NOVA CYBER-VAULT RUNTIME SDK 🛡️
 * Official TypeScript / Node.js Client Library
 * Lead Systems Architect: juniorsir
 */

import { spawnSync, execSync, spawn, ChildProcess } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';

export interface VesselOptions {
  mool?: string;          // Base rootfs (or '/' for live host testing)
  karya?: string;         // Command or script to execute
  sangjna?: string;       // UTS Container hostname
  smriti?: string;        // Memory quota (e.g. '512MB' with Sanjeevani auto-healing)
  shakti?: number;        // CPU core execution multiplier (e.g. 1.0, 2.0)
  kendra?: string;        // CPU Core Pinning (e.g. '0,1')
  tejas?: string;         // Hardware/GPU passthrough ('all')
  vayu?: string[];        // Ephemeral tmpfs RAM disk mounts
  gati?: string;          // Network bandwidth throttling limit
  bhaar?: string;         // Disk I/O read/write limit
  sthapana?: string;      // Packages to auto-install upon boot
  paryavaran?: Record<string, string>; // Environment variables

  // 🛡️ Elite Cybersecurity & Privacy Suite
  chhadm?: string;        // 🎭 MAC Spoofing ('random')
  gupt?: string;          // 🧅 Tor Transparent Tunnel ('tor')
  ekant?: boolean;        // 🏝️ Air-Gapped Solitude Mode (true = offline)
  bhasma?: boolean;       // 🔥 Anti-forensic RAM shredding (true = zero on exit)
  maya?: string;          // 🔮 Syscall Honeypot ('trap' / 'audit')

  // Hardening & Isolation
  sadasya?: string;       // User context ('root', 'sir', or UID)
  kavach?: string;        // Seccomp-BPF profile ('strict')
  adhikar?: string;       // Capability stripping ('-SYS_BOOT -SYS_TIME')
  kala?: string;          // Time namespace isolation ('virtual')
  suraksha?: string;      // Security policy ('ephemeral' / 'Standard Sandbox')
}

export class Vessel {
  private options: VesselOptions;
  private cardPath: string;

  constructor(options: VesselOptions = {}) {
    this.options = {
      mool: "/",
      karya: "/bin/bash",
      sangjna: "vault-node",
      smriti: "512MB",
      shakti: 1.0,
      sadasya: "root",
      kavach: "strict",
      ...options
    };
    this.cardPath = path.join('/tmp', `Patra.${Date.now()}.${Math.floor(Math.random() * 1000)}`);
  }

  /**
   * Generates the declarative YAML Patra manifest card on disk
   */
  public generateCard(): string {
    const lines: string[] = [
      `# Generated by @juniorsir/vessel-sdk`,
      `Mool: "${this.options.mool}"`,
      `Karya: "${this.options.karya}"`,
      `Sangjna: "${this.options.sangjna}"`,
      `Smriti: "${this.options.smriti}"`,
      `Shakti: ${this.options.shakti}`,
      `Sadasya: "${this.options.sadasya}"`,
    ];

    if (this.options.sthapana) lines.push(`Sthapana: "${this.options.sthapana}"`);
    if (this.options.kendra) lines.push(`Kendra: "${this.options.kendra}"`);
    if (this.options.tejas) lines.push(`Tejas: "${this.options.tejas}"`);
    if (this.options.gati) lines.push(`Gati: "${this.options.gati}"`);
    if (this.options.bhaar) lines.push(`Bhaar: "${this.options.bhaar}"`);
    if (this.options.kavach) lines.push(`Kavach: "${this.options.kavach}"`);
    if (this.options.adhikar) lines.push(`Adhikar: "${this.options.adhikar}"`);
    if (this.options.kala) lines.push(`Kala: "${this.options.kala}"`);
    if (this.options.suraksha) lines.push(`Suraksha: "${this.options.suraksha}"`);

    // Cybersecurity Suite
    if (this.options.chhadm) lines.push(`Chhadm: "${this.options.chhadm}"`);
    if (this.options.gupt) lines.push(`Gupt: "${this.options.gupt}"`);
    if (this.options.ekant) lines.push(`Ekant: "true"`);
    if (this.options.bhasma) lines.push(`Bhasma: "true"`);
    if (this.options.maya) lines.push(`Maya: "${this.options.maya}"`);

    if (this.options.vayu && this.options.vayu.length > 0) {
      lines.push(`Vayu:`);
      this.options.vayu.forEach(v => lines.push(`  - "${v}"`));
    }

    if (this.options.paryavaran) {
      lines.push(`Paryavaran:`);
      for (const [k, v] of Object.entries(this.options.paryavaran)) {
        lines.push(`  ${k}: "${v}"`);
      }
    }

    const yaml = lines.join('\n') + '\n';
    fs.writeFileSync(this.cardPath, yaml);
    return yaml;
  }

  /**
   * Boots the sandbox synchronously and returns stdout/stderr
   */
  public runSync(quiet: boolean = false): { stdout: string; stderr: string; status: number | null } {
    this.generateCard();
    const args = quiet ? ['-q', this.cardPath] : [this.cardPath];
    const result = spawnSync('sudo', ['vessel', ...args], { encoding: 'utf-8' });
    this.clean();
    return { stdout: result.stdout, stderr: result.stderr, status: result.status };
  }

  /**
   * Deletes the ephemeral manifest card
   */
  public clean(): void {
    if (fs.existsSync(this.cardPath)) {
      fs.unlinkSync(this.cardPath);
    }
  }

  /**
   * Static helper: Execute instant 1-word commands
   */
  public static cleanAll(): void {
    execSync('sudo vessel clean', { stdio: 'inherit' });
  }

  public static launchTor(): void {
    execSync('sudo vessel tor', { stdio: 'inherit' });
  }

  public static runDiagnosticTest(): void {
    execSync('sudo vessel test', { stdio: 'inherit' });
  }
}
